// This file is generated by rust-protobuf 2.17.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![rustfmt::skip]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `tensorflow/core/protobuf/critical_section.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_17_0;

#[derive(PartialEq,Clone,Default)]
pub struct CriticalSectionDef {
    // message fields
    pub critical_section_name: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a CriticalSectionDef {
    fn default() -> &'a CriticalSectionDef {
        <CriticalSectionDef as ::protobuf::Message>::default_instance()
    }
}

impl CriticalSectionDef {
    pub fn new() -> CriticalSectionDef {
        ::std::default::Default::default()
    }

    // string critical_section_name = 1;


    pub fn get_critical_section_name(&self) -> &str {
        &self.critical_section_name
    }
    pub fn clear_critical_section_name(&mut self) {
        self.critical_section_name.clear();
    }

    // Param is passed by value, moved
    pub fn set_critical_section_name(&mut self, v: ::std::string::String) {
        self.critical_section_name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_critical_section_name(&mut self) -> &mut ::std::string::String {
        &mut self.critical_section_name
    }

    // Take field
    pub fn take_critical_section_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.critical_section_name, ::std::string::String::new())
    }
}

impl ::protobuf::Message for CriticalSectionDef {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.critical_section_name)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.critical_section_name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.critical_section_name);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.critical_section_name.is_empty() {
            os.write_string(1, &self.critical_section_name)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> CriticalSectionDef {
        CriticalSectionDef::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "critical_section_name",
                |m: &CriticalSectionDef| { &m.critical_section_name },
                |m: &mut CriticalSectionDef| { &mut m.critical_section_name },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<CriticalSectionDef>(
                "CriticalSectionDef",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static CriticalSectionDef {
        static instance: ::protobuf::rt::LazyV2<CriticalSectionDef> = ::protobuf::rt::LazyV2::INIT;
        instance.get(CriticalSectionDef::new)
    }
}

impl ::protobuf::Clear for CriticalSectionDef {
    fn clear(&mut self) {
        self.critical_section_name.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for CriticalSectionDef {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CriticalSectionDef {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct CriticalSectionExecutionDef {
    // message fields
    pub execute_in_critical_section_name: ::std::string::String,
    pub exclusive_resource_access: bool,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a CriticalSectionExecutionDef {
    fn default() -> &'a CriticalSectionExecutionDef {
        <CriticalSectionExecutionDef as ::protobuf::Message>::default_instance()
    }
}

impl CriticalSectionExecutionDef {
    pub fn new() -> CriticalSectionExecutionDef {
        ::std::default::Default::default()
    }

    // string execute_in_critical_section_name = 1;


    pub fn get_execute_in_critical_section_name(&self) -> &str {
        &self.execute_in_critical_section_name
    }
    pub fn clear_execute_in_critical_section_name(&mut self) {
        self.execute_in_critical_section_name.clear();
    }

    // Param is passed by value, moved
    pub fn set_execute_in_critical_section_name(&mut self, v: ::std::string::String) {
        self.execute_in_critical_section_name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_execute_in_critical_section_name(&mut self) -> &mut ::std::string::String {
        &mut self.execute_in_critical_section_name
    }

    // Take field
    pub fn take_execute_in_critical_section_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.execute_in_critical_section_name, ::std::string::String::new())
    }

    // bool exclusive_resource_access = 2;


    pub fn get_exclusive_resource_access(&self) -> bool {
        self.exclusive_resource_access
    }
    pub fn clear_exclusive_resource_access(&mut self) {
        self.exclusive_resource_access = false;
    }

    // Param is passed by value, moved
    pub fn set_exclusive_resource_access(&mut self, v: bool) {
        self.exclusive_resource_access = v;
    }
}

impl ::protobuf::Message for CriticalSectionExecutionDef {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.execute_in_critical_section_name)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.exclusive_resource_access = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.execute_in_critical_section_name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.execute_in_critical_section_name);
        }
        if self.exclusive_resource_access != false {
            my_size += 2;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.execute_in_critical_section_name.is_empty() {
            os.write_string(1, &self.execute_in_critical_section_name)?;
        }
        if self.exclusive_resource_access != false {
            os.write_bool(2, self.exclusive_resource_access)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> CriticalSectionExecutionDef {
        CriticalSectionExecutionDef::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "execute_in_critical_section_name",
                |m: &CriticalSectionExecutionDef| { &m.execute_in_critical_section_name },
                |m: &mut CriticalSectionExecutionDef| { &mut m.execute_in_critical_section_name },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                "exclusive_resource_access",
                |m: &CriticalSectionExecutionDef| { &m.exclusive_resource_access },
                |m: &mut CriticalSectionExecutionDef| { &mut m.exclusive_resource_access },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<CriticalSectionExecutionDef>(
                "CriticalSectionExecutionDef",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static CriticalSectionExecutionDef {
        static instance: ::protobuf::rt::LazyV2<CriticalSectionExecutionDef> = ::protobuf::rt::LazyV2::INIT;
        instance.get(CriticalSectionExecutionDef::new)
    }
}

impl ::protobuf::Clear for CriticalSectionExecutionDef {
    fn clear(&mut self) {
        self.execute_in_critical_section_name.clear();
        self.exclusive_resource_access = false;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for CriticalSectionExecutionDef {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CriticalSectionExecutionDef {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n/tensorflow/core/protobuf/critical_section.proto\x12\ntensorflow\"H\n\
    \x12CriticalSectionDef\x122\n\x15critical_section_name\x18\x01\x20\x01(\
    \tR\x13criticalSectionName\"\xa1\x01\n\x1bCriticalSectionExecutionDef\
    \x12F\n\x20execute_in_critical_section_name\x18\x01\x20\x01(\tR\x1cexecu\
    teInCriticalSectionName\x12:\n\x19exclusive_resource_access\x18\x02\x20\
    \x01(\x08R\x17exclusiveResourceAccessBt\n\x18org.tensorflow.frameworkB\
    \x15CriticalSectionProtosP\x01Z<github.com/tensorflow/tensorflow/tensorf\
    low/go/core/protobuf\xf8\x01\x01b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
