// This file is generated by rust-protobuf 2.17.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![rustfmt::skip]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `tensorflow/compiler/tf2tensorrt/utils/trt_engine_instance.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_17_0;

#[derive(PartialEq,Clone,Default)]
pub struct TRTEngineInstance {
    // message fields
    pub input_shapes: ::protobuf::RepeatedField<super::tensor_shape::TensorShapeProto>,
    pub serialized_engine: ::std::vec::Vec<u8>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a TRTEngineInstance {
    fn default() -> &'a TRTEngineInstance {
        <TRTEngineInstance as ::protobuf::Message>::default_instance()
    }
}

impl TRTEngineInstance {
    pub fn new() -> TRTEngineInstance {
        ::std::default::Default::default()
    }

    // repeated .tensorflow.TensorShapeProto input_shapes = 1;


    pub fn get_input_shapes(&self) -> &[super::tensor_shape::TensorShapeProto] {
        &self.input_shapes
    }
    pub fn clear_input_shapes(&mut self) {
        self.input_shapes.clear();
    }

    // Param is passed by value, moved
    pub fn set_input_shapes(&mut self, v: ::protobuf::RepeatedField<super::tensor_shape::TensorShapeProto>) {
        self.input_shapes = v;
    }

    // Mutable pointer to the field.
    pub fn mut_input_shapes(&mut self) -> &mut ::protobuf::RepeatedField<super::tensor_shape::TensorShapeProto> {
        &mut self.input_shapes
    }

    // Take field
    pub fn take_input_shapes(&mut self) -> ::protobuf::RepeatedField<super::tensor_shape::TensorShapeProto> {
        ::std::mem::replace(&mut self.input_shapes, ::protobuf::RepeatedField::new())
    }

    // bytes serialized_engine = 2;


    pub fn get_serialized_engine(&self) -> &[u8] {
        &self.serialized_engine
    }
    pub fn clear_serialized_engine(&mut self) {
        self.serialized_engine.clear();
    }

    // Param is passed by value, moved
    pub fn set_serialized_engine(&mut self, v: ::std::vec::Vec<u8>) {
        self.serialized_engine = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_serialized_engine(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.serialized_engine
    }

    // Take field
    pub fn take_serialized_engine(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.serialized_engine, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for TRTEngineInstance {
    fn is_initialized(&self) -> bool {
        for v in &self.input_shapes {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.input_shapes)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.serialized_engine)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.input_shapes {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        if !self.serialized_engine.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.serialized_engine);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.input_shapes {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        if !self.serialized_engine.is_empty() {
            os.write_bytes(2, &self.serialized_engine)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TRTEngineInstance {
        TRTEngineInstance::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::tensor_shape::TensorShapeProto>>(
                "input_shapes",
                |m: &TRTEngineInstance| { &m.input_shapes },
                |m: &mut TRTEngineInstance| { &mut m.input_shapes },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "serialized_engine",
                |m: &TRTEngineInstance| { &m.serialized_engine },
                |m: &mut TRTEngineInstance| { &mut m.serialized_engine },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<TRTEngineInstance>(
                "TRTEngineInstance",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static TRTEngineInstance {
        static instance: ::protobuf::rt::LazyV2<TRTEngineInstance> = ::protobuf::rt::LazyV2::INIT;
        instance.get(TRTEngineInstance::new)
    }
}

impl ::protobuf::Clear for TRTEngineInstance {
    fn clear(&mut self) {
        self.input_shapes.clear();
        self.serialized_engine.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TRTEngineInstance {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TRTEngineInstance {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n?tensorflow/compiler/tf2tensorrt/utils/trt_engine_instance.proto\x12\
    \x13tensorflow.tensorrt\x1a,tensorflow/core/framework/tensor_shape.proto\
    \"\x81\x01\n\x11TRTEngineInstance\x12?\n\x0cinput_shapes\x18\x01\x20\x03\
    (\x0b2\x1c.tensorflow.TensorShapeProtoR\x0binputShapes\x12+\n\x11seriali\
    zed_engine\x18\x02\x20\x01(\x0cR\x10serializedEngineb\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
